//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusDayOff
    {
        public int ID { get; set; }
        public byte TotalDates { get; set; }
        public string Description { get; set; }
        public string CreateTime { get; set; }
        public int CreateUser_ID { get; set; }
        public int Employee_ID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
